### PR TITLE
Fix misformatting of token.

### LINKED ISSUE #12: Refuses to run.
I downloaded every single version of the stateye.exe file and none of them did anything, just a small blue circle on the cursor for a second and then nothing. I also tried running the debug application and it showed that there were no errors. Any fix?

Specs:
Ryzen 7 5700X
NVIDIA RTX 3070 Ti
16GB Ram.

Help would be extremely appreciated :)

### PR DESCRIPTION
**Pull request by GunnableScum**
Changes the .ROBLOSECURITY token should it be misformatted. Will probably close #12 and #15.
[Also for issue #12, the Program runs in the Background, it has no UI and can only be ended using Task-Manager or `taskkill -f -im stateye.exe`]

### CODE REVIEW

**Comment by GunnableScum** [comment]
(Also for context, I'm using Rust for the First time, I usually code in Java, so I had some troubles along the way but managed to do this)

File: src/roblox.rs [hunk 1]
```diff
@@ -35,7 +35,9 @@ pub struct UserPresence {
 /// 
 /// eg. `"secret"` -> `".ROBLOSECURITY=secret"`
 fn token_to_cookie(token: &str) -> String {
-	format!(".ROBLOSECURITY={}", token)
+	// Change some possible misformatting when copying the token
+	let token_cookie = format!(".ROBLOSECURITY={}", token).replace(".ROBLOSECURITY=.ROBLOSECURITY=", ".ROBLOSECURITY=").replace("^", "");
```
Comment (Daw588) [inline src/roblox.rs:39]: Could you explain why we are removing duplicate ".ROBLOSECURITY=", is it always coming with its own ".ROBLOSECURITY=", or does this behavior vary?

**Review by Daw588 — CHANGES_REQUESTED** [review]
I really appreciate your help with the fix. Before I can merge this, I have left one question in my review that I would like to have it answered.

File: src/roblox.rs (hunk 1 above)
Comment (GunnableScum) [reply src/roblox.rs:39]: I made this change because in some cases when when you copy the cookie, the ".ROBLOSECURITY=" comes with it. 

(i.e. Copy it from the Network Tab, which would look like this: 
".ROBLOSECURITY=\_^|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.^|\_[CENSORED]") 

So to answer your Question, it depends on how you, as a user would copy the cookie.

Comment (GunnableScum) [reply src/roblox.rs:39]: Also, if you want, I could combine the Variable Delaration and return call into a singular return call, I just used println for debugging, which is why it's there.

Comment (Daw588) [reply src/roblox.rs]: Sorry for late reply, I had to fix my GPG key for signing commits. I have made several improvements to the pull request.

**Comment by GunnableScum** [comment]
Thank you, have a nice day!
